# 129 — GNN Behaviour Cloning analysis

Episode `78867640`, focus step **35**.

- Load `128-GNN_BC/model_epoch100.pt`
- `reachable_max_ships` filtered to my planets at step 35
- `actions_to_copy` ground truth
- Model predictions with probabilities

In [1]:
import sys
import importlib.util
import math
import numpy as np
import polars as pl
import pandas as pd
import torch
from pathlib import Path

# Load 128-GNN_BC as a module (name starts with digit, use importlib)
spec = importlib.util.spec_from_file_location('gnn_bc', '128-GNN_BC.py')
gnn_bc = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gnn_bc)
sys.modules['gnn_bc'] = gnn_bc  # torch_geometric Inspector resolves type hints via sys.modules

GNNBehaviourCloning = gnn_bc.GNNBehaviourCloning
build_graph         = gnn_bc.build_graph
load_episode        = gnn_bc.load_episode

EPISODE    = 78867640
FOCUS_STEP = 35
PRE_DIR    = Path(f'126-precompute/{EPISODE}')
MODEL_PATH = Path('128-GNN_BC/model_epoch100.pt')

In [2]:
planete, planete_step, reachable_base_2, reachable_max_ships, actions_to_copy = load_episode(PRE_DIR)

for name, df in [
    ('planete',             planete),
    ('planete_step',        planete_step),
    ('reachable_base_2',    reachable_base_2),
    ('reachable_max_ships', reachable_max_ships),
    ('actions_to_copy',     actions_to_copy),
]:
    print(f'{name:25s}  {str(df.shape):18s}  cols: {df.columns}')

planete                    (17268, 6)          cols: ['id', 'step', 'x', 'y', 'production', 'nature']
planete_step               (344988, 5)         cols: ['id', 'step', 'future_step', 'ships', 'owner']
reachable_base_2           (4172992, 5)        cols: ['id_src', 'step_src', 'id_tgt', 'step_tgt', 'ships_sent']
reachable_max_ships        (284012, 6)         cols: ['id_src', 'step_src', 'angle', 'ships_sent', 'id_tgt', 'step_tgt']
actions_to_copy            (88, 5)             cols: ['step', 'id_src', 'angle', 'ships_sent', 'id_tgt']

In [14]:
planete_step.to_pandas().query("step == @FOCUS_STEP and future_step == @FOCUS_STEP")

        id  step  future_step  ships  owner
7541    18    35           35      1      0
8920    12    35           35      2      0
35200   24    35           35     14     -1
38034   14    35           35      8     -1
74638    9    35           35     85     -1
133790  15    35           35      3      1
155931  30    35           35     28     -1
158601   7    35           35     45     -1
169836   8    35           35     85     -1
174099  21    35           35     11      1
188343  29    35           35     28     -1
198785  25    35           35     14     -1
215779  27    35           35     14     -1
219011   5    35           35     45     -1
222445  20    35           35     30      0
230957  22    35           35     11      0
236144  31    35           35     28     -1
236363  10    35           35     85     -1
243226   2    35           35     43     -1
243526   1    35           35     43     -1
245102  16    35           35      9     -1
265627   0    35           35     43     -1
266127  11    35           35     85     -1
275782  23    35           35     42      1
294474  13    35           35      8     -1
295711  28    35           35     28     -1
301425  26    35           35     14     -1
310033   3    35           35     43     -1
310633  17    35           35      1      1
319437  19    35           35      9     -1
325974   6    35           35     45     -1
339377   4    35           35     45     -1

## My planets at step 35

In [3]:
T = FOCUS_STEP

ps_now = planete_step.filter(
    (pl.col('step') == T) & (pl.col('future_step') == T)
)
my_planet_ids = ps_now.filter(pl.col('owner') == 0)['id'].to_list()
print(f'My planets at step {T}: {sorted(my_planet_ids)}')

ps_now.sort('id').to_pandas()

My planets at step 35: [12, 18, 20, 22]

    id  step  future_step  ships  owner
0    0    35           35     43     -1
1    1    35           35     43     -1
2    2    35           35     43     -1
3    3    35           35     43     -1
4    4    35           35     45     -1
5    5    35           35     45     -1
6    6    35           35     45     -1
7    7    35           35     45     -1
8    8    35           35     85     -1
9    9    35           35     85     -1
10  10    35           35     85     -1
11  11    35           35     85     -1
12  12    35           35      2      0
13  13    35           35      8     -1
14  14    35           35      8     -1
15  15    35           35      3      1
16  16    35           35      9     -1
17  17    35           35      1      1
18  18    35           35      1      0
19  19    35           35      9     -1
20  20    35           35     30      0
21  21    35           35     11      1
22  22    35           35     11      0
23  23    35           35     42      1
24  24    35           35     14     -1
25  25    35           35     14     -1
26  26    35           35     14     -1
27  27    35           35     14     -1
28  28    35           35     28     -1
29  29    35           35     28     -1
30  30    35           35     28     -1
31  31    35           35     28     -1

## `reachable_max_ships` — owned by me, step_src == 35

In [4]:
reachable_mine = reachable_max_ships.filter(
    (pl.col('step_src') == T) & (pl.col('id_src').is_in(my_planet_ids))
).sort(['id_src', 'id_tgt'])

print(f'{len(reachable_mine)} candidate actions from my {len(my_planet_ids)} planet(s)')
reachable_mine.to_pandas()

39 candidate actions from my 4 planet(s)

    id_src  step_src     angle  ships_sent  id_tgt  step_tgt
0       12        35 -3.003457           2       1        54
1       12        35  2.096969           2       5        49
2       12        35  0.435150           2      14        54
3       12        35  0.800887           2      18        51
4       12        35  1.207544           2      20        38
5       12        35  2.810567           2      25        49
6       12        35  0.033505           2      30        54
7       18        35  1.459978           1       0        46
8       18        35 -0.048997           1       4        54
9       18        35 -1.751253           1      14        40
10      18        35 -0.922103           1      22        42
11      18        35  0.521219           1      24        45
12      20        35  0.378453          30       0        49
13      20        35 -2.762599          30       1        46
14      20        35  2.667450          30       5        41
15      20        35  1.884890          30       9        40
16      20        35 -2.206205          30      12        42
17      20        35 -0.024747          30      14        45
18      20        35 -0.502090          30      15        55
19      20        35 -2.044459          30      16        51
20      20        35  0.295896          30      18        43
21      20        35 -0.298712          30      19        55
22      20        35 -0.010278          30      22        48
23      20        35  0.180269          30      24        52
24      20        35 -3.022365          30      25        43
25      20        35 -1.771009          30      28        42
26      20        35 -0.350442          30      30        45
27      20        35 -0.650166          30      31        53
28      22        35  1.949790          11       0        50
29      22        35 -1.192344          11       2        54
30      22        35  1.096654          11       4        42
31      22        35  0.314094          11       8        41
32      22        35  2.634934          11      14        50
33      22        35 -1.564367          11      15        47
34      22        35 -1.222580          11      19        45
35      22        35 -1.542386          11      23        49
36      22        35  1.690023          11      24        46
37      22        35  2.903917          11      30        47
38      22        35 -1.923703          11      31        47

## `actions_to_copy` — ground truth at step 35

In [5]:
actions_35 = actions_to_copy.filter(pl.col('step') == T)
print(f'{len(actions_35)} ground truth action(s) at step {T}')
actions_35.to_pandas()

1 ground truth action(s) at step 35

   step  id_src   angle  ships_sent  id_tgt
0    35      18 -1.4326          18      14

## Load model — epoch 100

In [6]:
model = GNNBehaviourCloning(
    H  = gnn_bc.HIDDEN_DIM,
    L1 = gnn_bc.NUM_LAYERS_P1,
    L2 = gnn_bc.NUM_LAYERS_P2,
)
state_dict = torch.load(MODEL_PATH, map_location='cpu', weights_only=True)
model.load_state_dict(state_dict)
model.eval()

n_params = sum(p.numel() for p in model.parameters())
print(f'Loaded  : {MODEL_PATH}')
print(f'Params  : {n_params:,}')

Loaded  : 128-GNN_BC\model_epoch100.pt
Params  : 142,785

## Build graph for step 35 and run inference

In [7]:
graph = build_graph(
    T,
    planete, planete_step, reachable_base_2, reachable_max_ships, actions_to_copy
)
assert graph is not None, 'build_graph returned None — no action_max nodes at this step'

n_ams = graph['action_max'].x.shape[0]
n_pos = int(graph['action_max'].y.sum().item())
print(f'planet nodes       : {graph["planet"].x.shape[0]}')
print(f'planet_step nodes  : {graph["planet_step"].x.shape[0]}')
print(f'action_max nodes   : {n_ams}  (positives={n_pos})')
print()
print(graph)

planet nodes       : 32
planet_step nodes  : 672
action_max nodes   : 39  (positives=1)

HeteroData(
  planet={ x=[32, 4] },
  planet_step={ x=[672, 9] },
  action_max={
    x=[39, 1],
    y=[39],
  },
  (planet, has_ps, planet_step)={ edge_index=[2, 672] },
  (planet_step, rev_has_ps, planet)={ edge_index=[2, 672] },
  (planet_step, reaches, planet_step)={
    edge_index=[2, 23859],
    edge_attr=[23859],
  },
  (planet_step, src_of, action_max)={ edge_index=[2, 39] },
  (action_max, rev_src_of, planet_step)={ edge_index=[2, 39] },
  (planet_step, tgt_of, action_max)={ edge_index=[2, 39] },
  (action_max, rev_tgt_of, planet_step)={ edge_index=[2, 39] }
)

In [8]:
with torch.no_grad():
    logits = model(graph)          # (n_ams,)
    probs  = torch.sigmoid(logits).numpy()

print(f'logits : [{logits.min():.3f}, {logits.max():.3f}]')
print(f'probs  : [{probs.min():.3f}, {probs.max():.3f}]')

logits : [-5.605, 4.764]
probs  : [0.004, 0.992]

## Predicted actions vs ground truth

Reconstruct which `(id_src, id_tgt)` corresponds to each `action_max` node
by replicating the validity filter from `build_graph`.

In [9]:
# ── Rebuild PS key index ──────────────────────────────────────────────────────
ps_raw          = planete_step.filter(pl.col('step') == T)
ps_ids_np       = ps_raw['id'].to_numpy()
ps_fstep_np     = ps_raw['future_step'].to_numpy()
ps_key_to_idx   = {
    (int(ps_ids_np[i]), int(ps_fstep_np[i])): i
    for i in range(len(ps_raw))
}

# ── ams_labeled (same join as in build_graph) ─────────────────────────────────
ams_raw = reachable_max_ships.filter(
    (pl.col('step_src') == T) & (pl.col('id_src').is_in(my_planet_ids))
)
act_flag = (
    actions_to_copy
    .filter(pl.col('step') == T)
    .select(['id_src', 'id_tgt'])
    .with_columns(pl.lit(1).alias('_match'))
)
ams_labeled = (
    ams_raw
    .join(act_flag, on=['id_src', 'id_tgt'], how='left')
    .with_columns(label=pl.col('_match').fill_null(0).cast(pl.Int64))
    .drop('_match')
)

# ── Validity filter: same as build_graph valid_ams_rows ───────────────────────
id_src_np   = ams_labeled['id_src'].to_numpy()
id_tgt_np   = ams_labeled['id_tgt'].to_numpy()
step_tgt_np = ams_labeled['step_tgt'].to_numpy()

valid_rows = [
    i for i in range(len(ams_labeled))
    if ps_key_to_idx.get((int(id_src_np[i]), T), -1) >= 0
    and ps_key_to_idx.get((int(id_tgt_np[i]), int(step_tgt_np[i])), -1) >= 0
]

assert len(valid_rows) == n_ams, (
    f'Mismatch: valid_rows={len(valid_rows)}, action_max nodes={n_ams}'
)

# ── Attach predictions ────────────────────────────────────────────────────────
result = (
    ams_labeled[valid_rows]
    .with_columns([
        pl.Series('prob',      probs.tolist()),
        pl.Series('predicted', (probs >= 0.5).tolist()),
    ])
    .sort(['id_src', 'id_tgt'])
)

print(f'action_max nodes: {n_ams}  positives: {n_pos}  predicted positives: {int((probs>=0.5).sum())}')
result.to_pandas()

action_max nodes: 39  positives: 1  predicted positives: 10

,id_src,step_src,angle,ships_sent,id_tgt,step_tgt,label,prob,predicted
0,12,35,-3.003457,2,1,54,0,0.058981,False
1,12,35,2.096969,2,5,49,0,0.874946,True
2,12,35,0.435150,2,14,54,0,0.951336,True
3,12,35,0.800887,2,18,51,0,0.928941,True
4,12,35,1.207544,2,20,38,0,0.989987,True
5,12,35,2.810567,2,25,49,0,0.057621,False
6,12,35,0.033505,2,30,54,0,0.083908,False
7,18,35,1.459978,1,0,46,0,0.879820,True
8,18,35,-0.048997,1,4,54,0,0.987658,True
9,18,35,-1.751253,1,14,40,1,0.991545,True
10,18,35,-0.922103,1,22,42,0,0.991540,True
11,18,35,0.521219,1,24,45,0,0.863965,True
12,20,35,0.378453,30,0,49,0,0.003728,False
13,20,35,-2.762599,30,1,46,0,0.003674,False
14,20,35,2.667450,30,5,41,0,0.011575,False
15,20,35,1.884890,30,9,40,0,0.003735,False
16,20,35,-2.206205,30,12,42,0,0.245603,False
17,20,35,-0.024747,30,14,45,0,0.143913,False
18,20,35,-0.502090,30,15,55,0,0.011097,False
19,20,35,-2.044459,30,16,51,0,0.003773,False
20,20,35,0.295896,30,18,43,0,0.104842,False
21,20,35,-0.298712,30,19,55,0,0.003756,False
22,20,35,-0.010278,30,22,48,0,0.064532,False
23,20,35,0.180269,30,24,52,0,0.003684,False
24,20,35,-3.022365,30,25,43,0,0.003666,False
25,20,35,-1.771009,30,28,42,0,0.003780,False
26,20,35,-0.350442,30,30,45,0,0.003826,False
27,20,35,-0.650166,30,31,53,0,0.003756,False
28,22,35,1.949790,11,0,50,0,0.004507,False
29,22,35,-1.192344,11,2,54,0,0.004247,False
30,22,35,1.096654,11,4,42,0,0.045018,False
31,22,35,0.314094,11,8,41,0,0.004430,False
32,22,35,2.634934,11,14,50,0,0.262906,False
33,22,35,-1.564367,11,15,47,0,0.467863,False
34,22,35,-1.222580,11,19,45,0,0.004739,False
35,22,35,-1.542386,11,23,49,0,0.567677,True
36,22,35,1.690023,11,24,46,0,0.004404,False
37,22,35,2.903917,11,30,47,0,0.004773,False
38,22,35,-1.923703,11,31,47,0,0.004700,False

## Positives only — ground truth and predicted side by side

In [10]:
pos_gt   = result.filter(pl.col('label') == 1)
pos_pred = result.filter(pl.col('predicted') == True)

print('=== Ground truth positive actions ===')
display(pos_gt.select(['id_src','id_tgt','ships_sent','step_tgt','prob','label']).to_pandas())

print('=== Predicted positive actions (prob >= 0.5) ===')
display(pos_pred.select(['id_src','id_tgt','ships_sent','step_tgt','prob','label']).to_pandas())

# ── top-k by prob ─────────────────────────────────────────────────────────────
print('=== Top 10 by probability ===')
display(
    result
    .sort('prob', descending=True)
    .head(10)
    .select(['id_src','id_tgt','ships_sent','step_tgt','prob','label','predicted'])
    .to_pandas()
)

=== Ground truth positive actions ===

   id_src  id_tgt  ships_sent  step_tgt      prob  label
0      18      14           1        40  0.991545      1

=== Predicted positive actions (prob >= 0.5) ===

   id_src  id_tgt  ships_sent  step_tgt      prob  label
0      12       5           2        49  0.874946      0
1      12      14           2        54  0.951336      0
2      12      18           2        51  0.928941      0
3      12      20           2        38  0.989987      0
4      18       0           1        46  0.879820      0
5      18       4           1        54  0.987658      0
6      18      14           1        40  0.991545      1
7      18      22           1        42  0.991540      0
8      18      24           1        45  0.863965      0
9      22      23          11        49  0.567677      0

=== Top 10 by probability ===

   id_src  id_tgt  ships_sent  step_tgt      prob  label  predicted
0      18      14           1        40  0.991545      1       True
1      18      22           1        42  0.991540      0       True
2      12      20           2        38  0.989987      0       True
3      18       4           1        54  0.987658      0       True
4      12      14           2        54  0.951336      0       True
5      12      18           2        51  0.928941      0       True
6      18       0           1        46  0.879820      0       True
7      12       5           2        49  0.874946      0       True
8      18      24           1        45  0.863965      0       True
9      22      23          11        49  0.567677      0       True